### PR TITLE
Update logo images

### LINKED ISSUE #84: Update to the new protocol logo: moz://a
We should hold off on doing this until the font is ready so we can potentially use that. But I thought having an issue here to track it would be good.

/cc @craigcook @schalkneethling @bensternthal

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #84

Very simple update of the logo images. I used guides to approximate the position + height of the new logo on the same baseline. 

Happy to make adjustments if needed.

Before: 

screen shot 2017-02-22 at 16 55 56

After (click these to see where the whitespace is really at)

screen shot 2017-02-23 at 21 37 28

screen shot 2017-02-23 at 21 37 33

### CODE REVIEW

**Comment by fitojb** [comment]
According to mozilla.ninja, the rectangular highlight around the wordmark is integral part of the logo and must not be dropped. To avoid the tab look too busy, I think it would be a good idea to drop the Australis shape and make the tab rectangular.

**Comment by alexgibson** [comment]
> According to mozilla.ninja, the rectangular highlight around the wordmark is integral part of the logo and must not be dropped. To avoid the tab look too busy, I think it would be a good idea to drop the Australis shape and make the tab rectangular.

At this point, I do wonder if Tabzilla should still exist, as this basically just becomes the logo?

**Comment by muffinresearch** [comment]
> At this point, I do wonder if Tabzilla should still exist, as this basically just becomes the logo?

That's a fair point, however, one benefit of this project is that it resulted in consistency on all the sites that use it.

**Comment by muffinresearch** [comment]
Updated to use the new logo directly + updated CSS to make the color changes continue to work.

**Comment by craigcook** [comment]
We talked about this with some of the designers this morning and the direction was, instead of a tab, to make it a solid white bar all the way across the top with the black wordmark (black box with white text, that is). The bar should be about the height of the current tab, maybe a little smaller even, so the logo inside it probably needs to shrink a little to allow a bit of white space above and below.

@muffinresearch Do you want to work on revising this PR? Or if you've got better things to do we can close it and I might be able to pick this task up next week.

**Comment by muffinresearch** [comment]
@craigcook I'm happy to try that out tomorrow. Presumably the click target is just the logo and not the entire bar?

**Comment by craigcook** [comment]
Correct, just the logo.

**Comment by muffinresearch** [comment]
Updated to use black background + white text logo full-wdith bar version. 

It'll need an additional patch to change the docs to remove the references to being able to change the font color. Added some vars to make the heights easy to tweak. If there's someone from the design team who wants to precisely define those it's easy to update.

**Comment by alexgibson** [comment]
One question I now have, is how are sites that use navigation alongside the existing tabzilla wordmark supposed to use this new version, seeing as it runs full width of the viewport?

For example:
- https://mozillians.org/
- https://reps.mozilla.org/

If the idea is to now incorporate their navigation inside of the `#tabzilla` container, should we provide some basic direction in the docs? (this doesn't have to be part of this PR, but I thought we should ask the question before going forward with this direction).

**Comment by kyoshino** [comment]
Any updates?

**Comment by alexgibson** [comment]
The consensus here was that there's not much value in updating Tabzilla here, because it is essentially just the workmark now. Tabzilla itself is deprecated, and we'd like the fact that it is outdated visually to serve as a good reminder that it should be removed.

**Pull request closed without merging**
